version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - '8290:8290'
    restart: always
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: sh -c "sleep 5 && npx prisma generate && npx prisma db push && npm run start:dev"
    volumes:
      - ./dev.db:/app/dev.db

networks:
  default:
    driver: bridge
